openapi: 3.0.1
info:
  title: Jogo Seguro IA API
  description: API para monitoramento de atividades de apostas e geração de relatórios.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000
    description: Servidor Local
paths:
  /user/register:
    post:
      summary: Registrar Usuário
      description: Registra um novo usuário na plataforma.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        200:
          description: Usuário registrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user_id:
                    type: string
  /monitoring/activity:
    post:
      summary: Registrar Atividade de Jogo
      description: Registra o tempo de jogo de um usuário.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Monitoramento'
      responses:
        200:
          description: Atividade registrada com sucesso
  /monitoring/intervention/{user_id}:
    get:
      summary: Verificar Intervenção
      description: Retorna se o usuário está jogando por um período excessivo.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Retorna alerta de tempo de jogo
  /deposit/check:
    post:
      summary: Verificar Depósito
      description: Analisa se um depósito realizado pelo usuário é atípico.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Deposito'
      responses:
        200:
          description: Retorna se o depósito foi identificado como atípico
  /report/csv/{user_id}:
    get:
      summary: Gerar Relatório CSV
      description: Gera um relatório em formato CSV para um usuário específico.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Retorna o arquivo CSV
  /report/pdf/{user_id}:
    get:
      summary: Gerar Relatório PDF
      description: Gera um relatório em formato PDF para um usuário específico.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Retorna o arquivo PDF
components:
  schemas:
    Usuario:
      type: object
      properties:
        user_id:
          type: string
        nome:
          type: string
        email:
          type: string
        data_nascimento:
          type: string
    Monitoramento:
      type: object
      properties:
        user_id:
          type: string
        tempo_jogado_minutos:
          type: integer
    Deposito:
      type: object
      properties:
        user_id:
          type: string
        valor:
          type: number
